### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by themisir** [gigantz/react-downloadfile-hook#1]
Upon inspection I suspected that [the following snippet](https://github.com/gigantz/react-downloadfile-hook/blob/4e5a66e6f95e5a1c3e3dced9cf241d4a9759c5e0/src/index.ts#LL51C1-L51C1) may cause memory leaks if the created blob url is not revoked properly when the object is unmounted or when any of the properties change.

The reason is `URL.createObjectURL` allocates "system" (browser) resources that needed to be properly deallocated using `revokeObjectURL` method. More on object URL memory management can be found on [this MSDN docs page](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static#memory_management).

As a solution you may want to use combination of `useRef` to cache the value and `useEffect` to allocate and deallocate object URLs.

**Comment by gigantz** [comment]
Good catch! I was willing to do a graceful deallocating, but I haven’t decide yet on which cycle to do it.

The blob changes will need to rerender the component that uses **linkProps**, so **useRef** won’t help with that. Probably revoking it and recreating it on **deps** changes might work, that is what I was avoiding. But I will update it in a while.

Thanks for the issue! Feel free to contribute if there are anything to improve it or optimize.

**Comment by themisir** [comment]
> The blob changes will need to rerender the component that uses linkProps, so useRef won’t help with that. Probably revoking it and recreating it on deps changes might work, that is what I was avoiding. But I will update it in a while.

I was thinking of something like this:

```js
const urlRef = useRef();

useEffect(() => {
  const blobUrl = URL.createObjectURL(blob);
  urlRef.current = blobUrl;
  return () => URL.revokeObjectURL(blobUrl);
}, [blob]);
```

`useRef` is there just for holding the state. However, I guess `useState` hook may be a better fit instead.

**Comment by gigantz** [comment]
`useEffect` is calling cleanup deps change, so it will invalidate previous blob url that passed into a link component.
Yeah that is what I meant above, I will work with `useState` instead that will rerender the link with props. And yeah it will need to rerender the component, but it is a good trade-off anyway.

**Comment by gigantz** [comment]
Fixed in [[fix] Handling blob revoking & minor changes](https://github.com/gigantz/react-downloadfile-hook/commit/ea29d730845b0bdce7f129a7df2e1b63902951e8)
